### ISSUE TITLE
conda-installed gfortran on OSX: builds fail at runtime

### ISSUE THREAD

**Issue by hdrake** [ddbkoll/PyRADS#5]
See @brian-rose's [issue running into the same problem](https://github.com/ContinuumIO/anaconda-issues/issues/739) and the workaround he implemented in his [build script for the climlab package](https://github.com/brian-rose/climlab/blob/master/conda-recipe/build.sh).

**Comment by brian-rose** [comment]
Not sure about this. I implemented a hack in https://github.com/brian-rose/climlab/pull/41 to address the gfortran runtime issue described in https://github.com/ContinuumIO/anaconda-issues/issues/739.

But the need for that hack went away when I started using conda-build to build and test climlab, because the linking is fixed internally by conda-build.

The `if [[ `uname` == 'Darwin' ]]; then` clause in the climlab build script was just borrowed directly from [conda forge recipe for scipy](https://github.com/conda-forge/scipy-feedstock/blob/master/recipe/build.sh). I was never too clear what problem it was solving, but I'm pretty sure it's a different problem.

**Comment by brian-rose** [comment]
@hdrake did you find a solution to this?

I found the same runtime fail after following the PyRADS build procedure (using `gfortran_osx-64` from the conda-forge channel).

I tried fixing the linking by doing 
```
install_name_tool -change @rpath/./libgfortran.3.dylib ${CONDA_PREFIX}/lib/libgfortran.3.dylib -change @rpath/./libquadmath.0.dylib ${CONDA_PREFIX}/lib/libquadmath.0.dylib cntnm_v3.2_OS_X_gnu_dbl
```
following the advice in  ContinuumIO/anaconda-issues#739 but I still got runtime errors.

**Comment by hdrake** [comment]
@brian-rose, I also did not have any success with using
`install_name_tool -change @rpath/./libgfortran.3.dylib ${CONDA_PREFIX}/lib/libgfortran.3.dylib -change @rpath/./libquadmath.0.dylib ${CONDA_PREFIX}/lib/libquadmath.0.dylib cntnm_v3.2_OS_X_gnu_dbl`

I ended up just the default gfortran I have installed (I think from Xcode?) and used `export PATH=/usr/bin:$PATH`. That worked for me but it would be nice to be able to install / compile all of PyRADS with conda.

**Comment by brian-rose** [comment]
This will probably need to get solved as part of the packaging discussed in #6

**Comment by brian-rose** [comment]
I got this to work by changing the `osxGNUdbl` block of `makefile.common` to have the following line:
```
	FCFLAG=" -fdefault-integer-8 -fdefault-real-8 -frecord-marker=4 -Wl,-rpath,${CONDA_PREFIX}/lib" \
```

I also had to install `clang` by doing
``` 
conda install clang 
```

Everything worked as expected after that.

**Comment by brian-rose** [comment]
A short-term solution is probably just to add a new option to the makefile called `osxGNUdbl_conda` or something like that

**Comment by brian-rose** [comment]
@ddbkoll take a look at the pull request #8 that I just submitted. Doesn't change any of your code but should help other users get up and running quicker.
